version: 2.0.0-b{build}
before_build:
- ps: nuget restore
build:
  project: Bud.Exec.sln
  verbosity: minimal
before_package:
  - ps: cd Bud.Exec; nuget pack Bud.Exec.nuspec
artifacts:
  - path: Bud.Exec/bin/Debug/Bud.Exec.dll
    name: Bud.Exec.dll
  - path: Bud.Exec/bin/Debug/Bud.Exec.xml
    name: Bud.Exec.xml
  - path: 'Bud.Exec/*.nupkg'
deploy:
  provider: NuGet
  api_key:
    secure: vHH6XlHbTmh514SHTC2RTHVZmB+Tv+7WkhGT7Jz+ctyJyYfa9CbSukRVqYhWSh3e
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true