version: 2.0.0-b{build}
before_build:
- ps: nuget restore
build:
  project: Bud.Exec.sln
  verbosity: minimal
deploy: off
artifacts:
  - path: Bud.Exec/Bud.Exec/bin/Debug/Bud.Exec.dll
    name: Bud.Exec.dll
  - path: Bud.Exec/Bud.Exec/bin/Debug/Bud.Exec.xml
    name: Bud.Exec.xml