version: 2.1.2-b{build}
before_build:
- ps: nuget restore
build:
  project: Bud.Exec.sln
  verbosity: minimal
before_package:
  - ps: 'cd Bud.Exec; nuget pack Bud.Exec.csproj'
artifacts:
  - path: Bud.Exec/bin/Debug/Bud.Exec.dll
    name: Bud.Exec.dll
  - path: Bud.Exec/bin/Debug/Bud.Exec.xml
    name: Bud.Exec.xml
  - path: 'Bud.Exec/*.nupkg'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
deploy:
  provider: NuGet
  api_key:
    secure: vHH6XlHbTmh514SHTC2RTHVZmB+Tv+7WkhGT7Jz+ctyJyYfa9CbSukRVqYhWSh3e
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
